### PR TITLE
Fix URLs and filenames

### LINKED ISSUE #6: `brew install gitea` results in `404 Not Found`
Attempting to use this tap to install gitea results in a `404 Not Found` error, due to an invalid URL.

```
$ brew install gitea
==> Installing gitea from go-gitea/gitea
==> Downloading http://dl.gitea.io/gitea/1.0.0/gitea-1.0.0-darwin-amd64
==> Downloading from https://dl.gitea.io/gitea/1.0.0/gitea-1.0.0-darwin-amd64

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "gitea"
Download failed: http://dl.gitea.io/gitea/1.0.0/gitea-1.0.0-darwin-amd64
```

From what I can tell, it looks like the appropriate URL is `https://dl.gitea.io/gitea/1.0.0/gitea-1.0.0-darwin-10.6-amd64`

### PR DESCRIPTION
**Pull request by jorng**
Fixes #6 -- Actual filenames include `10.6` between `darwin` and `amd64`

### CODE REVIEW

**Comment by tboerger** [comment]
Thanks, I don't know how I missed that.
LGTM

**Comment by jorng** [comment]
Don't merge yet. The checksum still isn't working

**Comment by jorng** [comment]
Ok, looks like I have all of the install options working (stable, devel, head). Ready to verify and merge.

**Comment by lunny** [comment]
LGTM

**Comment by tboerger** [comment]
Small hint afterwards, the downloads page redirects to https, so if you define the URLs with https you can drop the `-L` from curl.

**Pull request merged**
