### PR TITLE
Make stable/devel/head installable

### LINKED ISSUE #3: Install stable, devel or head
Currently you can only install devel or head, but we have to be able to install also the stable branch.

### PR DESCRIPTION
**Pull request by tboerger**
Fixes #3

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
resolved by #7 and conflicted.

**Comment by tboerger** [comment]
I have applied all improvements and increased the version to 1.0.1

**Comment by lunny** [comment]
LGTM

**Comment by Bwko** [comment]
Trusted LGTM

**Pull request merged**
